/*
 * Copyright 2025 Polyas GmbH
 *
 * Licensed under GNU Affero General Public License v3.0; you may not use
 * this file except in compliance with the License. You may obtain a copy of
 * the License at https://www.gnu.org/licenses/agpl-3.0.en.html.
 * This software is distributed WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, 
 * either express or implied.
 */
package de.polyas.core3.crypto.elgamal.threshold

import de.polyas.core3.crypto.elgamal.zkp.DlogNIZKP
import java.math.BigInteger

/**
 * Data shared by one teller for another one in a threshold system.
 */
data class KeyGenSharedData<GroupElement>(
    /**
     * The number of the teller who produced (i.e. who shares) the data.
     */
    val producer: Int,

    /**
     * The value f(j) of the polynomial f owned by the producer, to be shared
     * with j-th teller, where j is not specified and must be clear from the
     * context.
     */
    val point: BigInteger,

    /**
     * Values g^{a_0}, ..., g^{a_t}, where each a_i is a coefficient of the
     * polynomial generated by the teller.
     */
    val blindedCoefficients: List<GroupElement>,

    /**
     * Non-interactivde zero-knowledge proofs of knowledge of the discrete logarithms of the [blindedCoefficients].
     */
    val pkCoefficients: List<DlogNIZKP.Proof>
)
