package de.polyas.core3.crypto.elgamal.threshold

import java.math.BigInteger

/**
 * Data shared by one teller for another one in a threshold system.
 */
data class KeyGenSharedData<GroupElement>(
    /**
     * The number of the teller who produced (i.e. who shares) the data.
     */
    val producer: Int,

    /**
     * The value f(j) of the polynomial f owned by the producer, to be shared
     * with j-th teller, where j is not specified and must be clear from the
     * context.
     */
    val point: BigInteger,

    /**
     * Values g^{a_0}, ..., g^{a_t}, where each a_i is a coefficient of the
     * polynomial generated by the teller.
     */
    val blindedCoefficients: List<GroupElement>
)